// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma 7's migrate engine reads ONLY `datasource.url` from this
    // config. A `directUrl` key here is silently ignored (not part of
    // the v7 PrismaConfig schema). So point `url` at DIRECT_URL — the
    // session-mode connection that supports advisory locks — and the
    // runtime PrismaClient in src/lib/prisma.ts continues to use
    // DATABASE_URL (the transaction pooler) via the pg adapter.
    url: env("DIRECT_URL"),
  },
});
